# Generated by Django 4.1.1 on 2022-09-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('bussiness_name', models.CharField(blank=True, max_length=225, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to='')),
                ('comment', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
