# Generated by Django 4.1.1 on 2022-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employee_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
