# Generated by Django 4.1.1 on 2022-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_marketing_researchlab_bookride'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
